import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <div style={{background:'#eee'}}>
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div>
      <nav>
        <ul>
          <li className="nav-list-item">Information</li>
          <li className="nav-list-item">After Party</li>
          <li className="nav-list-item">Location</li>
          <li className="nav-list-item">Gifts</li>
          <li className="nav-list-item">Questionaire</li>
          <li className="nav-list-item">RSVP</li>
        </ul>
      </nav>

      <div className={styles.grid} style={{width:'100%', background:'white'}}>
        <div className={styles.text}>
          <h2>Andy & Wiola </h2>
          <p>7th October</p>
          <button>RSVP</button>
        </div>
        <img className={styles.image} style={{height:400}} src="/hero-image.jpg" alt="" />
      </div>
      <main className={styles.main}>
      
      </main>
      </div>
    </>
    </div>
  )
}
